### ISSUE TITLE
bash-profile.stub should source ${HOME}/.bash-history-sqlite.sh

### ISSUE THREAD

**Issue by skissane** [thenewwazoo/bash-history-sqlite#1]
When you open a new tab in macOS Terminal.app, it will start bash in the new tab in the same directory as the old one. (The `update_terminal_cwd()` shell function is called by prompt_command which sends the current working directory to the terminal using an escape sequence.)

However, this means that when ./.bash_profile runs in the new terminal tab, the line `source ./.bash-history-sqlite.sh` will fail not being able to find `.bash-history-sqlite.sh` script unless the tab happens to be opening in the home directory

If you change that line to read `source "${HOME}/.bash-history-sqlite.sh"` the problem is resolved.

**Comment by skissane** [comment]
There is another related problem. `.bash-history-sqlite.sh` assumes it is running in home directory, but when creating new tab in macOS Terminal.app that isn't true. I think the solution is to replace all occurrences of `.bash-preexec.sh` in that file with `"${HOME}/.bash-preexec.sh"`

**Comment by thenewwazoo** [comment]
[Fixed!](https://github.com/thenewwazoo/bash-history-sqlite/commit/b1153f4d4e628fc15cb0835d62fa2d9e547705d8) Thank you for the report!
